# -*- coding: utf-8 -*-
"""FiscaisFim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19AHrwhcm1HFXUGumkUYyUiuLOvu4r-la
"""

import pandas as pd
import folium
from flask import Flask

app = Flask(__name__)

@app.route('/')
def mapa():
    # Caminho do arquivo CSV local
    csv_path = 'V:\\USHD\Fiscais\\coordenadas2.csv'

    # Lendo o arquivo CSV com a codificação correta
    df = pd.read_csv(csv_path, sep=';', encoding='latin1')

    # Criando o mapa
    mapa = folium.Map(location=[-23.5489, -46.6388], zoom_start=7)
    for index, row in df.iterrows():
        popup_text = f"{row['Nome']}<br>Data: {row['Data']}<br>Atividade: {row['Atividade']}"
        folium.Marker(
            location=[row["Latitude"], row["Longitude"]],
            popup=popup_text,
            icon=folium.Icon(color="blue")
        ).add_to(mapa)

    return mapa._repr_html_()

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)